ktor {
  deployment {
    port = 8089
    port = ${?PORT}
  }
  application {
    modules = [ com.example.ApplicationKt.module ]
  }
}

database {
  url = "jdbc:postgresql://localhost:5432/ktor_db"
  url = ${?DB_URL}
  driver = "org.postgresql.Driver"
  driver = ${?DB_DRIVER}
  user = "postgres"
  user = ${?DB_USER}
  password = "23230906"
  password = ${?DB_PASSWORD}
}

jwt {
  secret = "super-secret-jwt-key-change-me"
  secret = ${?JWT_SECRET}
  issuer = "kotlin2kt"
  issuer = ${?JWT_ISSUER}
  audience = "kotlin2kt-users"
  audience = ${?JWT_AUDIENCE}
  realm = "ktor-app"
  realm = ${?JWT_REALM}
}
